export const blogsData = [
  {
    id: 1,
    location: "Oxygen",
    district: "Chittagong",
    price: "15000",
    area: "1000sqf",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Numquam facilis mollitia asperiores cupiditate quaerat non error cumque, tempora dolorum sed laboriosam nesciunt pariatur praesentium suscipit deleniti quas, quisquam inventore ullam ex. Blanditiis beatae esse cum odio expedita cupiditate laboriosam error ullam assumenda, suscipit sed quos amet iure numquam eaque aspernatur?",
  },
  {
    id: 2,
    location: "Mirpur",
    district: "Dhaka",
    price: "15000",
    area: "1000sqf",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Numquam facilis mollitia asperiores cupiditate quaerat non error cumque, tempora dolorum sed laboriosam nesciunt pariatur praesentium suscipit deleniti quas, quisquam inventore ullam ex. Blanditiis beatae esse cum odio expedita cupiditate laboriosam error ullam assumenda, suscipit sed quos amet iure numquam eaque aspernatur?",
  },
  {
    id: 3,
    location: "Uttara",
    district: "Dhaka",
    price: "15000",
    area: "1000sqf",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Numquam facilis mollitia asperiores cupiditate quaerat non error cumque, tempora dolorum sed laboriosam nesciunt pariatur praesentium suscipit deleniti quas, quisquam inventore ullam ex. Blanditiis beatae esse cum odio expedita cupiditate laboriosam error ullam assumenda, suscipit sed quos amet iure numquam eaque aspernatur?",
  },
  {
    id: 4,
    location: "Muradpur",
    district: "Chittagong",
    price: "15000",
    area: "1000sqf",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Numquam facilis mollitia asperiores cupiditate quaerat non error cumque, tempora dolorum sed laboriosam nesciunt pariatur praesentium suscipit deleniti quas, quisquam inventore ullam ex. Blanditiis beatae esse cum odio expedita cupiditate laboriosam error ullam assumenda, suscipit sed quos amet iure numquam eaque aspernatur?",
  },
  {
    id: 5,
    location: "Agrabad",
    district: "Chittagong",
    price: "15000",
    area: "1000sqf",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Numquam facilis mollitia asperiores cupiditate quaerat non error cumque, tempora dolorum sed laboriosam nesciunt pariatur praesentium suscipit deleniti quas, quisquam inventore ullam ex. Blanditiis beatae esse cum odio expedita cupiditate laboriosam error ullam assumenda, suscipit sed quos amet iure numquam eaque aspernatur?",
  },
  {
    id: 6,
    location: "GEC",
    district: "Chittagong",
    price: "15000",
    area: "1000sqf",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Numquam facilis mollitia asperiores cupiditate quaerat non error cumque, tempora dolorum sed laboriosam nesciunt pariatur praesentium suscipit deleniti quas, quisquam inventore ullam ex. Blanditiis beatae esse cum odio expedita cupiditate laboriosam error ullam assumenda, suscipit sed quos amet iure numquam eaque aspernatur?",
  },
  {
    id: 7,
    location: "Hathazari",
    district: "Chittagong",
    price: "15000",
    area: "1000sqf",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Numquam facilis mollitia asperiores cupiditate quaerat non error cumque, tempora dolorum sed laboriosam nesciunt pariatur praesentium suscipit deleniti quas, quisquam inventore ullam ex. Blanditiis beatae esse cum odio expedita cupiditate laboriosam error ullam assumenda, suscipit sed quos amet iure numquam eaque aspernatur?",
  },
  {
    id: 8,
    location: "Jamalkahn",
    district: "Chittagong",
    price: "15000",
    area: "1000sqf",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Numquam facilis mollitia asperiores cupiditate quaerat non error cumque, tempora dolorum sed laboriosam nesciunt pariatur praesentium suscipit deleniti quas, quisquam inventore ullam ex. Blanditiis beatae esse cum odio expedita cupiditate laboriosam error ullam assumenda, suscipit sed quos amet iure numquam eaque aspernatur?",
  },
];
